sudo: true
env:
language: c
compiler: arm-linux-gnueabi-gcc
before_install:
- export PATH=$PATH:$HOME/.local/bin
- sudo apt-get install gcc-arm-linux-gnueabihf
script:
- ./autogen.sh --with-jemalloc-prefix=je_ --with-malloc-conf=purge:decay
- make
- cd lib
- ls -alrt
- file libjemalloc.so.2
 
