sudo: true
env:
language: c
compiler: /usr/bin/i586-mingw32msvc-gcc
before_install:
- export PATH=$PATH:$HOME/.local/bin
- sudo apt-get install mingw32
script:
- ./autogen.sh --with-jemalloc-prefix=je_ --with-malloc-conf=purge:decay --host=mingw32
- make
- cd lib
- ls -alrt
- file jemalloc.dll
 
