sudo: false
env:
language: c
compiler: gcc-arm-linux-gnueabihf
before_install:
- export PATH=$PATH:$HOME/.local/bin
- apt-get install gcc-arm-linux-gnueabihf
script:
- ./autogen.sh --with-jemalloc-prefix=je_ --with-malloc-conf=purge:decay
- make
- cd lib
- ls -alrt
- file libjemalloc.so.2
