sudo: true
env:
language: c
compiler: arm-linux-androideabi-gcc
before_install:
- export PATH=$PATH:$HOME/.local/bin
- export ANDROID_NDK_VERSION=r9c
- echo $ANDROID_NDK_VERSION
- if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-$ANDROID_NDK_VERSION-linux-x86.tar.bz2 -O ndk.tgz; fi
- tar -xf ndk.tgz
- export ANDROID_NDK_HOME=`pwd`/android-ndk-$ANDROID_NDK_VERSION
- export $ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME:PATH=${PATH}
script:
- ./autogen.sh --with-jemalloc-prefix=je_ --with-malloc-conf=purge:decay --host=arm-linux-androideabi
- make
- cd lib
- ls -alrt
- file libjemalloc.so.2
 
