sudo: false
env:
language: c
compiler: gcc
before_install:
- export PATH=$PATH:$HOME/.local/bin
script:
- ./autogen.sh --with-jemalloc-prefix=je_ --with-malloc-conf=purge:decay --host=arm-wrs-linux-gnueabi
- make
- cd lib
- ls -alrt
- file libjemalloc.so.2
